"""add product_id to monitoring_history

Revision ID: 53fc4aac8d5e
Revises: 8b2ac9f2d15f
Create Date: 2026-07-31 16:25:17.462943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53fc4aac8d5e'
down_revision: Union[str, Sequence[str], None] = '8b2ac9f2d15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_history', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'monitoring_history', 'tracked_products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monitoring_history', type_='foreignkey')
    op.drop_column('monitoring_history', 'product_id')
    # ### end Alembic commands ###
