"""add notified to monitoring_history

Revision ID: 678c8d9776f6
Revises: e68c33f66561
Create Date: 2026-07-31 16:52:31.762731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678c8d9776f6'
down_revision: Union[str, Sequence[str], None] = 'e68c33f66561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_history', sa.Column('notified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_history', 'notified')
    # ### end Alembic commands ###
