"""add target_price to tracked_products

Revision ID: e68c33f66561
Revises: 53fc4aac8d5e
Create Date: 2026-07-31 16:34:01.896559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68c33f66561'
down_revision: Union[str, Sequence[str], None] = '53fc4aac8d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_products', sa.Column('target_price', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_products', 'target_price')
    # ### end Alembic commands ###
